// Assets/Editor/SpecData/CodeGenerator.cs
using System.Collections.Generic;
using System.IO;
using System.Text;

namespace SpecData.EditorTools
{
    public static class CodeGenerator
    {
        const string HEADER =
@"// <auto-generated>
// Generated by SpecTableImporter. Do not edit.
// </auto-generated>
";

        public static void WriteEnums(IList<EnumDef> defs, string path, string ns = "SpecData")
        {
            var sb = new StringBuilder();
            sb.Append(HEADER);
            sb.Append("namespace ").Append(ns).AppendLine();
            sb.AppendLine("{");
            foreach (var def in defs)
            {
                sb.Append("    public enum ").Append(def.Name).AppendLine(" : int");
                sb.AppendLine("    {");
                foreach (var (key, val) in def.Entries)
                    sb.Append("        ").Append(key).Append(" = ").Append(val).AppendLine(",");
                sb.AppendLine("    }");
                sb.AppendLine();
            }
            sb.AppendLine("}");
            WriteFile(path, sb.ToString());
        }

        public static void WriteClass(TableSchema schema, string path, string ns = "SpecData")
        {
            var sb = new StringBuilder();
            sb.Append(HEADER);
            sb.AppendLine("using System;");
            sb.AppendLine();
            sb.Append("namespace ").Append(ns).AppendLine();
            sb.AppendLine("{");
            sb.AppendLine("    [Serializable]");
            sb.Append("    public partial class ").AppendLine(schema.TableName);
            sb.AppendLine("    {");
            foreach (var f in schema.Fields)
                sb.Append("        public ").Append(f.Type.ToCSharp()).Append(" ")
                  .Append(f.Name).AppendLine(";");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            WriteFile(path, sb.ToString());
        }

        /// <summary>
        /// SpecDataManager partial 을 생성한다.
        /// 각 테이블마다 프로퍼티 + Addressable 로드 한 줄을 와이어링한다.
        /// </summary>
        public static void WriteManagerTables(
            IList<TableSchema> schemas, string path, string ns, string addressPrefix)
        {
            var sb = new StringBuilder();
            sb.Append(HEADER);
            sb.AppendLine();
            sb.Append("namespace ").Append(ns).AppendLine();
            sb.AppendLine("{");
            sb.AppendLine("    public partial class SpecDataManager");
            sb.AppendLine("    {");

            // properties
            foreach (var s in schemas)
            {
                var key = ResolveKey(s);
                if (key.Field == null)
                {
                    sb.Append("        // SKIP ").Append(s.TableName)
                      .AppendLine(": no keyable field (int/long/string).");
                    continue;
                }
                sb.Append("        public Table<").Append(key.CSharpType).Append(", ")
                  .Append(s.TableName).Append("> ").Append(PropName(s.TableName))
                  .AppendLine(" { get; private set; }");
            }
            sb.AppendLine();

            sb.AppendLine("        partial void LoadTables()");
            sb.AppendLine("        {");
            foreach (var s in schemas)
            {
                var key = ResolveKey(s);
                if (key.Field == null) continue;
                sb.Append("            ").Append(PropName(s.TableName))
                  .Append(" = Table<").Append(key.CSharpType).Append(", ").Append(s.TableName)
                  .Append(">.LoadAddressable(\"").Append(addressPrefix).Append(s.TableName)
                  .Append("\", x => x.").Append(key.Field.Name).AppendLine(");");
            }
            sb.AppendLine("        }");
            sb.AppendLine();

            sb.AppendLine("        partial void UnloadTables()");
            sb.AppendLine("        {");
            foreach (var s in schemas)
            {
                var key = ResolveKey(s);
                if (key.Field == null) continue;
                sb.Append("            ").Append(PropName(s.TableName)).AppendLine(" = null;");
            }
            sb.AppendLine("        }");

            sb.AppendLine("    }");
            sb.AppendLine("}");
            WriteFile(path, sb.ToString());
        }

        struct KeyInfo { public Field Field; public string CSharpType; }

        static KeyInfo ResolveKey(TableSchema s)
        {
            Field preferred = null;
            foreach (var f in s.Fields)
                if (f.Name == "id" && IsKeyable(f)) { preferred = f; break; }

            if (preferred == null)
                foreach (var f in s.Fields)
                    if (IsKeyable(f)) { preferred = f; break; }

            return preferred == null
                ? default
                : new KeyInfo { Field = preferred, CSharpType = preferred.Type.ToCSharp() };
        }

        static bool IsKeyable(Field f)
        {
            if (f.Type.IsArray) return false;
            var p = f.Type.Prim;
            return p == Primitive.Int || p == Primitive.Long || p == Primitive.String;
        }

        static string PropName(string tableName)
        {
            if (tableName.Length >= 2 && tableName[0] == 'T' && char.IsUpper(tableName[1]))
                return tableName.Substring(1);
            return tableName;
        }

        static void WriteFile(string path, string content)
        {
            var dir = Path.GetDirectoryName(path);
            if (!string.IsNullOrEmpty(dir) && !Directory.Exists(dir)) Directory.CreateDirectory(dir);
            File.WriteAllText(path, content, Encoding.UTF8);
        }
    }
}
